version: '3.8'

services:
  idea-collector:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - idea-data:/app/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  idea-data:
    driver: local
